# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/impish64"

	config.ssh.insert_key = false

	#config.vm.define "wordPress" do |webSite|
	#	webSite.vm.hostname = "resume"
	#	webSite.vm.network :private_network, ip: "192.168.56.7"
	#end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "main.yml"
		ansible.vault_password_file = "~/.ansible/vault_pass"
	end
end
