# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	config.ssh.insert_key = false

	config.vm.define "mysql" do |database|
		database.vm.hostname = "mysqlDB"
		database.vm.network :private_network, ip: "192.168.56.3"
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "playbook.yml"
		ansible.vault_password_file = "~/.ansible/vault_pass"
	end
end
