---
- hosts: all
  become: yes
  tasks:
    - name: Update System
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Apache
      package: 
        name: apache2 
        state: present
        
    - name: Ensure Apache is running and starts at boot
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy web site
      copy:
        src: ~/Shared/School/Summer 2021/cs510Project/
        dest: /var/www/html