# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	config.ssh.insert_key = false

	config.vm.define "webSite" do |webSite|
		webSite.vm.hostname = "resume"
		webSite.vm.network :private_network, ip: "192.168.56.2"
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "playbook.yml"
	end
end
